/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java101;

import java.math.BigDecimal;
import java.math.RoundingMode;

public class PrimitiveTypes {

    public static void main(String[] args) {
        String text = "Any text you want";
        char character = 'C';
        int number = 10;
        boolean result= true;
        float floatNumber = 3.455f;

        System.out.println("String: " + text);
        System.out.println("Integer: " + number);
        System.out.println("Boolean: " + result);
        System.out.println("Char: " + character);
        System.out.println("Float: " + floatNumber);

        double doubleNumber = 0.02;
        double doubleNumber2 = 0.03;
        double resultDouble = doubleNumber2 - doubleNumber;

        System.out.println("Double: " + doubleNumber);
        System.out.println("Another Double " + doubleNumber2);
        System.out.println("Result Double: "+ resultDouble);

        BigDecimal bigNumber = new BigDecimal("0.02");
        BigDecimal bigNumber2 = new BigDecimal("0.03");
        BigDecimal resultBigNumber = bigNumber2.subtract(bigNumber);


        System.out.println("BigDecimal: " + bigNumber);
        System.out.println("Another BigDecimal: " + bigNumber2);
        System.out.println("Result BigDecimal: " + resultBigNumber);
        System.out.println("Result BigDecimal Another precision: " + resultBigNumber.setScale(10, RoundingMode.HALF_UP));

    }

}
