/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java101;

import java.math.BigDecimal;

public class PrimitiveTypes {

    public static void main(String[] args) {
        String text = "Any text you want";
        char character = 'C';
        int number = 10;
        boolean result= true;
        float floatNumber = 3.455f;

        double doubleNumber = 0.02;
        double doubleNumber2 = 0.03;
        double resultDouble = doubleNumber2 - doubleNumber;

        BigDecimal bigNumber = new BigDecimal("0.02");
        BigDecimal bigNumber2 = new BigDecimal("0.03");
        BigDecimal resultBigNumber = bigNumber2.subtract(bigNumber);


        System.out.println(text);
        System.out.println(number);
        System.out.println(result);
        System.out.println(doubleNumber);
        System.out.println(character);
        System.out.println(floatNumber);
        System.out.println(bigNumber);
        System.out.println(resultDouble);
        System.out.println(resultBigNumber);
    }

}
