/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java101;

public class PrimitiveTypes {

    public static void main(String[] args) {
        String text = "Any text you want";
        char character = 'C';
        int number = 10;
        boolean result= true;
        double doubleNumber = 3.455;
        float floatNumber = 3.455f;

        System.out.println(text);
        System.out.println(number);
        System.out.println(result);
        System.out.println(doubleNumber);
        System.out.println(character);
        System.out.println(floatNumber);
    }

}
